"""Update sensors

Revision ID: 291e2d7b1f0a
Revises: 4e2e5981df3d
Create Date: 2025-06-26 22:12:11.500208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '291e2d7b1f0a'
down_revision = '4e2e5981df3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('metric')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metric', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False))

    # ### end Alembic commands ###
