"""Update sensors

Revision ID: 4e2e5981df3d
Revises: f236279130f0
Create Date: 2025-06-26 22:03:35.600226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e2e5981df3d'
down_revision = 'f236279130f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metric', sa.String(length=64), nullable=False))

    with op.batch_alter_table('water_quality', schema=None) as batch_op:
        batch_op.alter_column('site_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_quality', schema=None) as batch_op:
        batch_op.alter_column('site_name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=True)

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('metric')

    # ### end Alembic commands ###
